package gov.polisen.orm.maps;

import gov.polisen.orm.clients.CaseSqlProvider;
import gov.polisen.orm.examples.CaseExample;
import gov.polisen.orm.models.Case;
import gov.polisen.orm.models.CaseKey;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;

public interface CaseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@SelectProvider(type = CaseSqlProvider.class, method = "countByExample")
	int countByExample(CaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Insert({
			"insert into cases (deviceid, caseid, ",
			"author, modificationtime, ",
			"firstrevisioncaseid, firstrevisiondeviceid, ",
			"deletiontime, classification, ",
			"status, priority, ",
			"longitude, latitude, timeofcrime, ",
			"description)",
			"values (#{deviceid,jdbcType=INTEGER}, #{caseid,jdbcType=INTEGER}, ",
			"#{author,jdbcType=INTEGER}, #{modificationtime,jdbcType=TIMESTAMP}, ",
			"#{firstrevisioncaseid,jdbcType=INTEGER}, #{firstrevisiondeviceid,jdbcType=INTEGER}, ",
			"#{deletiontime,jdbcType=TIMESTAMP}, #{classification,jdbcType=SMALLINT}, ",
			"#{status,jdbcType=SMALLINT}, #{priority,jdbcType=SMALLINT}, ",
			"#{longitude,jdbcType=REAL}, #{latitude,jdbcType=REAL}, #{timeofcrime,jdbcType=TIMESTAMP}, ",
			"#{description,jdbcType=VARCHAR})" })
	int insert(Case record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@InsertProvider(type = CaseSqlProvider.class, method = "insertSelective")
	int insertSelective(Case record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@SelectProvider(type = CaseSqlProvider.class, method = "selectByExample")
	@ConstructorArgs({
			@Arg(column = "deviceid", javaType = Integer.class, jdbcType = JdbcType.INTEGER, id = true),
			@Arg(column = "caseid", javaType = Integer.class, jdbcType = JdbcType.INTEGER, id = true),
			@Arg(column = "author", javaType = Integer.class, jdbcType = JdbcType.INTEGER),
			@Arg(column = "modificationtime", javaType = Date.class, jdbcType = JdbcType.TIMESTAMP),
			@Arg(column = "firstrevisioncaseid", javaType = Integer.class, jdbcType = JdbcType.INTEGER),
			@Arg(column = "firstrevisiondeviceid", javaType = Integer.class, jdbcType = JdbcType.INTEGER),
			@Arg(column = "deletiontime", javaType = Date.class, jdbcType = JdbcType.TIMESTAMP),
			@Arg(column = "classification", javaType = Short.class, jdbcType = JdbcType.SMALLINT),
			@Arg(column = "status", javaType = Short.class, jdbcType = JdbcType.SMALLINT),
			@Arg(column = "priority", javaType = Short.class, jdbcType = JdbcType.SMALLINT),
			@Arg(column = "longitude", javaType = Float.class, jdbcType = JdbcType.REAL),
			@Arg(column = "latitude", javaType = Float.class, jdbcType = JdbcType.REAL),
			@Arg(column = "timeofcrime", javaType = Date.class, jdbcType = JdbcType.TIMESTAMP),
			@Arg(column = "description", javaType = String.class, jdbcType = JdbcType.VARCHAR) })
	List<Case> selectByExample(CaseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Select({
			"select",
			"deviceid, caseid, author, modificationtime, firstrevisioncaseid, firstrevisiondeviceid, ",
			"deletiontime, classification, status, priority, longitude, latitude, timeofcrime, ",
			"description", "from cases",
			"where deviceid = #{deviceid,jdbcType=INTEGER}",
			"and caseid = #{caseid,jdbcType=INTEGER}" })
	@ConstructorArgs({
			@Arg(column = "deviceid", javaType = Integer.class, jdbcType = JdbcType.INTEGER, id = true),
			@Arg(column = "caseid", javaType = Integer.class, jdbcType = JdbcType.INTEGER, id = true),
			@Arg(column = "author", javaType = Integer.class, jdbcType = JdbcType.INTEGER),
			@Arg(column = "modificationtime", javaType = Date.class, jdbcType = JdbcType.TIMESTAMP),
			@Arg(column = "firstrevisioncaseid", javaType = Integer.class, jdbcType = JdbcType.INTEGER),
			@Arg(column = "firstrevisiondeviceid", javaType = Integer.class, jdbcType = JdbcType.INTEGER),
			@Arg(column = "deletiontime", javaType = Date.class, jdbcType = JdbcType.TIMESTAMP),
			@Arg(column = "classification", javaType = Short.class, jdbcType = JdbcType.SMALLINT),
			@Arg(column = "status", javaType = Short.class, jdbcType = JdbcType.SMALLINT),
			@Arg(column = "priority", javaType = Short.class, jdbcType = JdbcType.SMALLINT),
			@Arg(column = "longitude", javaType = Float.class, jdbcType = JdbcType.REAL),
			@Arg(column = "latitude", javaType = Float.class, jdbcType = JdbcType.REAL),
			@Arg(column = "timeofcrime", javaType = Date.class, jdbcType = JdbcType.TIMESTAMP),
			@Arg(column = "description", javaType = String.class, jdbcType = JdbcType.VARCHAR) })
	Case selectByPrimaryKey(CaseKey key);
}