package gov.polisen.orm.maps;

import gov.polisen.orm.clients.CaseImageSqlProvider;
import gov.polisen.orm.examples.CaseImageExample;
import gov.polisen.orm.models.CaseImage;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.type.JdbcType;

public interface CaseImageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caseimages
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@SelectProvider(type = CaseImageSqlProvider.class, method = "countByExample")
	int countByExample(CaseImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caseimages
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Insert({ "insert into caseimages (imageid, caseid, ", "deviceid)",
			"values (#{imageid,jdbcType=INTEGER}, #{caseid,jdbcType=INTEGER}, ",
			"#{deviceid,jdbcType=INTEGER})" })
	int insert(CaseImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caseimages
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@InsertProvider(type = CaseImageSqlProvider.class, method = "insertSelective")
	int insertSelective(CaseImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caseimages
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@SelectProvider(type = CaseImageSqlProvider.class, method = "selectByExample")
	@ConstructorArgs({
			@Arg(column = "imageid", javaType = Integer.class, jdbcType = JdbcType.INTEGER),
			@Arg(column = "caseid", javaType = Integer.class, jdbcType = JdbcType.INTEGER),
			@Arg(column = "deviceid", javaType = Integer.class, jdbcType = JdbcType.INTEGER) })
	List<CaseImage> selectByExample(CaseImageExample example);
}