package gov.polisen.orm.maps;

import gov.polisen.orm.clients.ClassificationSqlProvider;
import gov.polisen.orm.examples.ClassificationExample;
import gov.polisen.orm.models.Classification;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ClassificationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classifications
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@SelectProvider(type = ClassificationSqlProvider.class, method = "countByExample")
	int countByExample(ClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classifications
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@DeleteProvider(type = ClassificationSqlProvider.class, method = "deleteByExample")
	int deleteByExample(ClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classifications
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Delete({ "delete from classifications", "where id = #{id,jdbcType=SMALLINT}" })
	int deleteByPrimaryKey(Short id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classifications
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Insert({ "insert into classifications (id, shorthand, ", "description)",
			"values (#{id,jdbcType=SMALLINT}, #{shorthand,jdbcType=VARCHAR}, ",
			"#{description,jdbcType=VARCHAR})" })
	int insert(Classification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classifications
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@InsertProvider(type = ClassificationSqlProvider.class, method = "insertSelective")
	int insertSelective(Classification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classifications
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@SelectProvider(type = ClassificationSqlProvider.class, method = "selectByExample")
	@ConstructorArgs({
			@Arg(column = "id", javaType = Short.class, jdbcType = JdbcType.SMALLINT, id = true),
			@Arg(column = "shorthand", javaType = String.class, jdbcType = JdbcType.VARCHAR),
			@Arg(column = "description", javaType = String.class, jdbcType = JdbcType.VARCHAR) })
	List<Classification> selectByExample(ClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classifications
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Select({ "select", "id, shorthand, description", "from classifications",
			"where id = #{id,jdbcType=SMALLINT}" })
	@ConstructorArgs({
			@Arg(column = "id", javaType = Short.class, jdbcType = JdbcType.SMALLINT, id = true),
			@Arg(column = "shorthand", javaType = String.class, jdbcType = JdbcType.VARCHAR),
			@Arg(column = "description", javaType = String.class, jdbcType = JdbcType.VARCHAR) })
	Classification selectByPrimaryKey(Short id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classifications
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@UpdateProvider(type = ClassificationSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Classification record,
			@Param("example") ClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classifications
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@UpdateProvider(type = ClassificationSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Classification record,
			@Param("example") ClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classifications
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@UpdateProvider(type = ClassificationSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Classification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table classifications
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Update({ "update classifications",
			"set shorthand = #{shorthand,jdbcType=VARCHAR},",
			"description = #{description,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=SMALLINT}" })
	int updateByPrimaryKey(Classification record);
}