package gov.polisen.orm.maps;

import gov.polisen.orm.clients.DeviceSqlProvider;
import gov.polisen.orm.examples.DeviceExample;
import gov.polisen.orm.models.Device;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DeviceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table devices
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@SelectProvider(type = DeviceSqlProvider.class, method = "countByExample")
	int countByExample(DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table devices
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@DeleteProvider(type = DeviceSqlProvider.class, method = "deleteByExample")
	int deleteByExample(DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table devices
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Delete({ "delete from devices", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table devices
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Insert({ "insert into devices (id, lastseen, ", "battery, longitude, ",
			"latitude)",
			"values (#{id,jdbcType=INTEGER}, #{lastseen,jdbcType=TIMESTAMP}, ",
			"#{battery,jdbcType=SMALLINT}, #{longitude,jdbcType=REAL}, ",
			"#{latitude,jdbcType=REAL})" })
	int insert(Device record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table devices
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@InsertProvider(type = DeviceSqlProvider.class, method = "insertSelective")
	int insertSelective(Device record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table devices
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@SelectProvider(type = DeviceSqlProvider.class, method = "selectByExample")
	@ConstructorArgs({
			@Arg(column = "id", javaType = Integer.class, jdbcType = JdbcType.INTEGER, id = true),
			@Arg(column = "lastseen", javaType = Date.class, jdbcType = JdbcType.TIMESTAMP),
			@Arg(column = "battery", javaType = Short.class, jdbcType = JdbcType.SMALLINT),
			@Arg(column = "longitude", javaType = Float.class, jdbcType = JdbcType.REAL),
			@Arg(column = "latitude", javaType = Float.class, jdbcType = JdbcType.REAL) })
	List<Device> selectByExample(DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table devices
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Select({ "select", "id, lastseen, battery, longitude, latitude",
			"from devices", "where id = #{id,jdbcType=INTEGER}" })
	@ConstructorArgs({
			@Arg(column = "id", javaType = Integer.class, jdbcType = JdbcType.INTEGER, id = true),
			@Arg(column = "lastseen", javaType = Date.class, jdbcType = JdbcType.TIMESTAMP),
			@Arg(column = "battery", javaType = Short.class, jdbcType = JdbcType.SMALLINT),
			@Arg(column = "longitude", javaType = Float.class, jdbcType = JdbcType.REAL),
			@Arg(column = "latitude", javaType = Float.class, jdbcType = JdbcType.REAL) })
	Device selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table devices
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@UpdateProvider(type = DeviceSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Device record,
			@Param("example") DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table devices
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@UpdateProvider(type = DeviceSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Device record,
			@Param("example") DeviceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table devices
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@UpdateProvider(type = DeviceSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Device record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table devices
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Update({ "update devices", "set lastseen = #{lastseen,jdbcType=TIMESTAMP},",
			"battery = #{battery,jdbcType=SMALLINT},",
			"longitude = #{longitude,jdbcType=REAL},",
			"latitude = #{latitude,jdbcType=REAL}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Device record);
}