package gov.polisen.orm.maps;

import gov.polisen.orm.clients.PrioritySqlProvider;
import gov.polisen.orm.examples.PriorityExample;
import gov.polisen.orm.models.Priority;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PriorityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@SelectProvider(type = PrioritySqlProvider.class, method = "countByExample")
	int countByExample(PriorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@DeleteProvider(type = PrioritySqlProvider.class, method = "deleteByExample")
	int deleteByExample(PriorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Delete({ "delete from priorities", "where id = #{id,jdbcType=SMALLINT}" })
	int deleteByPrimaryKey(Short id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Insert({ "insert into priorities (id, shorthand, ", "description)",
			"values (#{id,jdbcType=SMALLINT}, #{shorthand,jdbcType=VARCHAR}, ",
			"#{description,jdbcType=VARCHAR})" })
	int insert(Priority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@InsertProvider(type = PrioritySqlProvider.class, method = "insertSelective")
	int insertSelective(Priority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@SelectProvider(type = PrioritySqlProvider.class, method = "selectByExample")
	@ConstructorArgs({
			@Arg(column = "id", javaType = Short.class, jdbcType = JdbcType.SMALLINT, id = true),
			@Arg(column = "shorthand", javaType = String.class, jdbcType = JdbcType.VARCHAR),
			@Arg(column = "description", javaType = String.class, jdbcType = JdbcType.VARCHAR) })
	List<Priority> selectByExample(PriorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Select({ "select", "id, shorthand, description", "from priorities",
			"where id = #{id,jdbcType=SMALLINT}" })
	@ConstructorArgs({
			@Arg(column = "id", javaType = Short.class, jdbcType = JdbcType.SMALLINT, id = true),
			@Arg(column = "shorthand", javaType = String.class, jdbcType = JdbcType.VARCHAR),
			@Arg(column = "description", javaType = String.class, jdbcType = JdbcType.VARCHAR) })
	Priority selectByPrimaryKey(Short id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@UpdateProvider(type = PrioritySqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Priority record,
			@Param("example") PriorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@UpdateProvider(type = PrioritySqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Priority record,
			@Param("example") PriorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@UpdateProvider(type = PrioritySqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Priority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	@Update({ "update priorities",
			"set shorthand = #{shorthand,jdbcType=VARCHAR},",
			"description = #{description,jdbcType=VARCHAR}",
			"where id = #{id,jdbcType=SMALLINT}" })
	int updateByPrimaryKey(Priority record);
}