package gov.polisen.orm.examples;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaseExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	protected String	orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	protected boolean	distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	protected List<Criteria>	oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public CaseExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion>	criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2,
				String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andDeviceidIsNull() {
			addCriterion("deviceid is null");
			return (Criteria) this;
		}

		public Criteria andDeviceidIsNotNull() {
			addCriterion("deviceid is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceidEqualTo(Integer value) {
			addCriterion("deviceid =", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidNotEqualTo(Integer value) {
			addCriterion("deviceid <>", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidGreaterThan(Integer value) {
			addCriterion("deviceid >", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidGreaterThanOrEqualTo(Integer value) {
			addCriterion("deviceid >=", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidLessThan(Integer value) {
			addCriterion("deviceid <", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidLessThanOrEqualTo(Integer value) {
			addCriterion("deviceid <=", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidIn(List<Integer> values) {
			addCriterion("deviceid in", values, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidNotIn(List<Integer> values) {
			addCriterion("deviceid not in", values, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidBetween(Integer value1, Integer value2) {
			addCriterion("deviceid between", value1, value2, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidNotBetween(Integer value1, Integer value2) {
			addCriterion("deviceid not between", value1, value2, "deviceid");
			return (Criteria) this;
		}

		public Criteria andCaseidIsNull() {
			addCriterion("caseid is null");
			return (Criteria) this;
		}

		public Criteria andCaseidIsNotNull() {
			addCriterion("caseid is not null");
			return (Criteria) this;
		}

		public Criteria andCaseidEqualTo(Integer value) {
			addCriterion("caseid =", value, "caseid");
			return (Criteria) this;
		}

		public Criteria andCaseidNotEqualTo(Integer value) {
			addCriterion("caseid <>", value, "caseid");
			return (Criteria) this;
		}

		public Criteria andCaseidGreaterThan(Integer value) {
			addCriterion("caseid >", value, "caseid");
			return (Criteria) this;
		}

		public Criteria andCaseidGreaterThanOrEqualTo(Integer value) {
			addCriterion("caseid >=", value, "caseid");
			return (Criteria) this;
		}

		public Criteria andCaseidLessThan(Integer value) {
			addCriterion("caseid <", value, "caseid");
			return (Criteria) this;
		}

		public Criteria andCaseidLessThanOrEqualTo(Integer value) {
			addCriterion("caseid <=", value, "caseid");
			return (Criteria) this;
		}

		public Criteria andCaseidIn(List<Integer> values) {
			addCriterion("caseid in", values, "caseid");
			return (Criteria) this;
		}

		public Criteria andCaseidNotIn(List<Integer> values) {
			addCriterion("caseid not in", values, "caseid");
			return (Criteria) this;
		}

		public Criteria andCaseidBetween(Integer value1, Integer value2) {
			addCriterion("caseid between", value1, value2, "caseid");
			return (Criteria) this;
		}

		public Criteria andCaseidNotBetween(Integer value1, Integer value2) {
			addCriterion("caseid not between", value1, value2, "caseid");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNull() {
			addCriterion("author is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNotNull() {
			addCriterion("author is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorEqualTo(Integer value) {
			addCriterion("author =", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotEqualTo(Integer value) {
			addCriterion("author <>", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThan(Integer value) {
			addCriterion("author >", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThanOrEqualTo(Integer value) {
			addCriterion("author >=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThan(Integer value) {
			addCriterion("author <", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThanOrEqualTo(Integer value) {
			addCriterion("author <=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorIn(List<Integer> values) {
			addCriterion("author in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotIn(List<Integer> values) {
			addCriterion("author not in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorBetween(Integer value1, Integer value2) {
			addCriterion("author between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotBetween(Integer value1, Integer value2) {
			addCriterion("author not between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andModificationtimeIsNull() {
			addCriterion("modificationtime is null");
			return (Criteria) this;
		}

		public Criteria andModificationtimeIsNotNull() {
			addCriterion("modificationtime is not null");
			return (Criteria) this;
		}

		public Criteria andModificationtimeEqualTo(Date value) {
			addCriterion("modificationtime =", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeNotEqualTo(Date value) {
			addCriterion("modificationtime <>", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeGreaterThan(Date value) {
			addCriterion("modificationtime >", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modificationtime >=", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeLessThan(Date value) {
			addCriterion("modificationtime <", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeLessThanOrEqualTo(Date value) {
			addCriterion("modificationtime <=", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeIn(List<Date> values) {
			addCriterion("modificationtime in", values, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeNotIn(List<Date> values) {
			addCriterion("modificationtime not in", values, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeBetween(Date value1, Date value2) {
			addCriterion("modificationtime between", value1, value2,
					"modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeNotBetween(Date value1, Date value2) {
			addCriterion("modificationtime not between", value1, value2,
					"modificationtime");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidIsNull() {
			addCriterion("firstrevisioncaseid is null");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidIsNotNull() {
			addCriterion("firstrevisioncaseid is not null");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidEqualTo(Integer value) {
			addCriterion("firstrevisioncaseid =", value, "firstrevisioncaseid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidNotEqualTo(Integer value) {
			addCriterion("firstrevisioncaseid <>", value, "firstrevisioncaseid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidGreaterThan(Integer value) {
			addCriterion("firstrevisioncaseid >", value, "firstrevisioncaseid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidGreaterThanOrEqualTo(Integer value) {
			addCriterion("firstrevisioncaseid >=", value, "firstrevisioncaseid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidLessThan(Integer value) {
			addCriterion("firstrevisioncaseid <", value, "firstrevisioncaseid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidLessThanOrEqualTo(Integer value) {
			addCriterion("firstrevisioncaseid <=", value, "firstrevisioncaseid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidIn(List<Integer> values) {
			addCriterion("firstrevisioncaseid in", values, "firstrevisioncaseid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidNotIn(List<Integer> values) {
			addCriterion("firstrevisioncaseid not in", values, "firstrevisioncaseid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidBetween(Integer value1, Integer value2) {
			addCriterion("firstrevisioncaseid between", value1, value2,
					"firstrevisioncaseid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisioncaseidNotBetween(Integer value1,
				Integer value2) {
			addCriterion("firstrevisioncaseid not between", value1, value2,
					"firstrevisioncaseid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidIsNull() {
			addCriterion("firstrevisiondeviceid is null");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidIsNotNull() {
			addCriterion("firstrevisiondeviceid is not null");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidEqualTo(Integer value) {
			addCriterion("firstrevisiondeviceid =", value, "firstrevisiondeviceid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidNotEqualTo(Integer value) {
			addCriterion("firstrevisiondeviceid <>", value, "firstrevisiondeviceid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidGreaterThan(Integer value) {
			addCriterion("firstrevisiondeviceid >", value, "firstrevisiondeviceid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidGreaterThanOrEqualTo(Integer value) {
			addCriterion("firstrevisiondeviceid >=", value, "firstrevisiondeviceid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidLessThan(Integer value) {
			addCriterion("firstrevisiondeviceid <", value, "firstrevisiondeviceid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidLessThanOrEqualTo(Integer value) {
			addCriterion("firstrevisiondeviceid <=", value, "firstrevisiondeviceid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidIn(List<Integer> values) {
			addCriterion("firstrevisiondeviceid in", values, "firstrevisiondeviceid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidNotIn(List<Integer> values) {
			addCriterion("firstrevisiondeviceid not in", values,
					"firstrevisiondeviceid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidBetween(Integer value1,
				Integer value2) {
			addCriterion("firstrevisiondeviceid between", value1, value2,
					"firstrevisiondeviceid");
			return (Criteria) this;
		}

		public Criteria andFirstrevisiondeviceidNotBetween(Integer value1,
				Integer value2) {
			addCriterion("firstrevisiondeviceid not between", value1, value2,
					"firstrevisiondeviceid");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeIsNull() {
			addCriterion("deletiontime is null");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeIsNotNull() {
			addCriterion("deletiontime is not null");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeEqualTo(Date value) {
			addCriterion("deletiontime =", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeNotEqualTo(Date value) {
			addCriterion("deletiontime <>", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeGreaterThan(Date value) {
			addCriterion("deletiontime >", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeGreaterThanOrEqualTo(Date value) {
			addCriterion("deletiontime >=", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeLessThan(Date value) {
			addCriterion("deletiontime <", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeLessThanOrEqualTo(Date value) {
			addCriterion("deletiontime <=", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeIn(List<Date> values) {
			addCriterion("deletiontime in", values, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeNotIn(List<Date> values) {
			addCriterion("deletiontime not in", values, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeBetween(Date value1, Date value2) {
			addCriterion("deletiontime between", value1, value2, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeNotBetween(Date value1, Date value2) {
			addCriterion("deletiontime not between", value1, value2, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andClassificationIsNull() {
			addCriterion("classification is null");
			return (Criteria) this;
		}

		public Criteria andClassificationIsNotNull() {
			addCriterion("classification is not null");
			return (Criteria) this;
		}

		public Criteria andClassificationEqualTo(Short value) {
			addCriterion("classification =", value, "classification");
			return (Criteria) this;
		}

		public Criteria andClassificationNotEqualTo(Short value) {
			addCriterion("classification <>", value, "classification");
			return (Criteria) this;
		}

		public Criteria andClassificationGreaterThan(Short value) {
			addCriterion("classification >", value, "classification");
			return (Criteria) this;
		}

		public Criteria andClassificationGreaterThanOrEqualTo(Short value) {
			addCriterion("classification >=", value, "classification");
			return (Criteria) this;
		}

		public Criteria andClassificationLessThan(Short value) {
			addCriterion("classification <", value, "classification");
			return (Criteria) this;
		}

		public Criteria andClassificationLessThanOrEqualTo(Short value) {
			addCriterion("classification <=", value, "classification");
			return (Criteria) this;
		}

		public Criteria andClassificationIn(List<Short> values) {
			addCriterion("classification in", values, "classification");
			return (Criteria) this;
		}

		public Criteria andClassificationNotIn(List<Short> values) {
			addCriterion("classification not in", values, "classification");
			return (Criteria) this;
		}

		public Criteria andClassificationBetween(Short value1, Short value2) {
			addCriterion("classification between", value1, value2, "classification");
			return (Criteria) this;
		}

		public Criteria andClassificationNotBetween(Short value1, Short value2) {
			addCriterion("classification not between", value1, value2,
					"classification");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNull() {
			addCriterion("priority is null");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNotNull() {
			addCriterion("priority is not null");
			return (Criteria) this;
		}

		public Criteria andPriorityEqualTo(Short value) {
			addCriterion("priority =", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotEqualTo(Short value) {
			addCriterion("priority <>", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThan(Short value) {
			addCriterion("priority >", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThanOrEqualTo(Short value) {
			addCriterion("priority >=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThan(Short value) {
			addCriterion("priority <", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThanOrEqualTo(Short value) {
			addCriterion("priority <=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityIn(List<Short> values) {
			addCriterion("priority in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotIn(List<Short> values) {
			addCriterion("priority not in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityBetween(Short value1, Short value2) {
			addCriterion("priority between", value1, value2, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotBetween(Short value1, Short value2) {
			addCriterion("priority not between", value1, value2, "priority");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNull() {
			addCriterion("longitude is null");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNotNull() {
			addCriterion("longitude is not null");
			return (Criteria) this;
		}

		public Criteria andLongitudeEqualTo(Float value) {
			addCriterion("longitude =", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotEqualTo(Float value) {
			addCriterion("longitude <>", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThan(Float value) {
			addCriterion("longitude >", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThanOrEqualTo(Float value) {
			addCriterion("longitude >=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThan(Float value) {
			addCriterion("longitude <", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThanOrEqualTo(Float value) {
			addCriterion("longitude <=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeIn(List<Float> values) {
			addCriterion("longitude in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotIn(List<Float> values) {
			addCriterion("longitude not in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeBetween(Float value1, Float value2) {
			addCriterion("longitude between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotBetween(Float value1, Float value2) {
			addCriterion("longitude not between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNull() {
			addCriterion("latitude is null");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNotNull() {
			addCriterion("latitude is not null");
			return (Criteria) this;
		}

		public Criteria andLatitudeEqualTo(Float value) {
			addCriterion("latitude =", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotEqualTo(Float value) {
			addCriterion("latitude <>", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThan(Float value) {
			addCriterion("latitude >", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThanOrEqualTo(Float value) {
			addCriterion("latitude >=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThan(Float value) {
			addCriterion("latitude <", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThanOrEqualTo(Float value) {
			addCriterion("latitude <=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeIn(List<Float> values) {
			addCriterion("latitude in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotIn(List<Float> values) {
			addCriterion("latitude not in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeBetween(Float value1, Float value2) {
			addCriterion("latitude between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotBetween(Float value1, Float value2) {
			addCriterion("latitude not between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeIsNull() {
			addCriterion("timeofcrime is null");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeIsNotNull() {
			addCriterion("timeofcrime is not null");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeEqualTo(Date value) {
			addCriterion("timeofcrime =", value, "timeofcrime");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeNotEqualTo(Date value) {
			addCriterion("timeofcrime <>", value, "timeofcrime");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeGreaterThan(Date value) {
			addCriterion("timeofcrime >", value, "timeofcrime");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeGreaterThanOrEqualTo(Date value) {
			addCriterion("timeofcrime >=", value, "timeofcrime");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeLessThan(Date value) {
			addCriterion("timeofcrime <", value, "timeofcrime");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeLessThanOrEqualTo(Date value) {
			addCriterion("timeofcrime <=", value, "timeofcrime");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeIn(List<Date> values) {
			addCriterion("timeofcrime in", values, "timeofcrime");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeNotIn(List<Date> values) {
			addCriterion("timeofcrime not in", values, "timeofcrime");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeBetween(Date value1, Date value2) {
			addCriterion("timeofcrime between", value1, value2, "timeofcrime");
			return (Criteria) this;
		}

		public Criteria andTimeofcrimeNotBetween(Date value1, Date value2) {
			addCriterion("timeofcrime not between", value1, value2, "timeofcrime");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public static class Criterion {
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

		/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cases
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 03 15:25:33 CEST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}