package gov.polisen.orm.examples;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeploymentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	protected String	orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	protected boolean	distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	protected List<Criteria>	oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public DeploymentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion>	criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2,
				String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNull() {
			addCriterion("author is null");
			return (Criteria) this;
		}

		public Criteria andAuthorIsNotNull() {
			addCriterion("author is not null");
			return (Criteria) this;
		}

		public Criteria andAuthorEqualTo(Integer value) {
			addCriterion("author =", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotEqualTo(Integer value) {
			addCriterion("author <>", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThan(Integer value) {
			addCriterion("author >", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorGreaterThanOrEqualTo(Integer value) {
			addCriterion("author >=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThan(Integer value) {
			addCriterion("author <", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorLessThanOrEqualTo(Integer value) {
			addCriterion("author <=", value, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorIn(List<Integer> values) {
			addCriterion("author in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotIn(List<Integer> values) {
			addCriterion("author not in", values, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorBetween(Integer value1, Integer value2) {
			addCriterion("author between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andAuthorNotBetween(Integer value1, Integer value2) {
			addCriterion("author not between", value1, value2, "author");
			return (Criteria) this;
		}

		public Criteria andModificationtimeIsNull() {
			addCriterion("modificationtime is null");
			return (Criteria) this;
		}

		public Criteria andModificationtimeIsNotNull() {
			addCriterion("modificationtime is not null");
			return (Criteria) this;
		}

		public Criteria andModificationtimeEqualTo(Date value) {
			addCriterion("modificationtime =", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeNotEqualTo(Date value) {
			addCriterion("modificationtime <>", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeGreaterThan(Date value) {
			addCriterion("modificationtime >", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modificationtime >=", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeLessThan(Date value) {
			addCriterion("modificationtime <", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeLessThanOrEqualTo(Date value) {
			addCriterion("modificationtime <=", value, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeIn(List<Date> values) {
			addCriterion("modificationtime in", values, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeNotIn(List<Date> values) {
			addCriterion("modificationtime not in", values, "modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeBetween(Date value1, Date value2) {
			addCriterion("modificationtime between", value1, value2,
					"modificationtime");
			return (Criteria) this;
		}

		public Criteria andModificationtimeNotBetween(Date value1, Date value2) {
			addCriterion("modificationtime not between", value1, value2,
					"modificationtime");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionIsNull() {
			addCriterion("firstrevision is null");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionIsNotNull() {
			addCriterion("firstrevision is not null");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionEqualTo(Integer value) {
			addCriterion("firstrevision =", value, "firstrevision");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionNotEqualTo(Integer value) {
			addCriterion("firstrevision <>", value, "firstrevision");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionGreaterThan(Integer value) {
			addCriterion("firstrevision >", value, "firstrevision");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionGreaterThanOrEqualTo(Integer value) {
			addCriterion("firstrevision >=", value, "firstrevision");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionLessThan(Integer value) {
			addCriterion("firstrevision <", value, "firstrevision");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionLessThanOrEqualTo(Integer value) {
			addCriterion("firstrevision <=", value, "firstrevision");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionIn(List<Integer> values) {
			addCriterion("firstrevision in", values, "firstrevision");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionNotIn(List<Integer> values) {
			addCriterion("firstrevision not in", values, "firstrevision");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionBetween(Integer value1, Integer value2) {
			addCriterion("firstrevision between", value1, value2, "firstrevision");
			return (Criteria) this;
		}

		public Criteria andFirstrevisionNotBetween(Integer value1, Integer value2) {
			addCriterion("firstrevision not between", value1, value2, "firstrevision");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeIsNull() {
			addCriterion("deletiontime is null");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeIsNotNull() {
			addCriterion("deletiontime is not null");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeEqualTo(Date value) {
			addCriterion("deletiontime =", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeNotEqualTo(Date value) {
			addCriterion("deletiontime <>", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeGreaterThan(Date value) {
			addCriterion("deletiontime >", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeGreaterThanOrEqualTo(Date value) {
			addCriterion("deletiontime >=", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeLessThan(Date value) {
			addCriterion("deletiontime <", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeLessThanOrEqualTo(Date value) {
			addCriterion("deletiontime <=", value, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeIn(List<Date> values) {
			addCriterion("deletiontime in", values, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeNotIn(List<Date> values) {
			addCriterion("deletiontime not in", values, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeBetween(Date value1, Date value2) {
			addCriterion("deletiontime between", value1, value2, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andDeletiontimeNotBetween(Date value1, Date value2) {
			addCriterion("deletiontime not between", value1, value2, "deletiontime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNull() {
			addCriterion("priority is null");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNotNull() {
			addCriterion("priority is not null");
			return (Criteria) this;
		}

		public Criteria andPriorityEqualTo(Short value) {
			addCriterion("priority =", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotEqualTo(Short value) {
			addCriterion("priority <>", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThan(Short value) {
			addCriterion("priority >", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThanOrEqualTo(Short value) {
			addCriterion("priority >=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThan(Short value) {
			addCriterion("priority <", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThanOrEqualTo(Short value) {
			addCriterion("priority <=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityIn(List<Short> values) {
			addCriterion("priority in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotIn(List<Short> values) {
			addCriterion("priority not in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityBetween(Short value1, Short value2) {
			addCriterion("priority between", value1, value2, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotBetween(Short value1, Short value2) {
			addCriterion("priority not between", value1, value2, "priority");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNull() {
			addCriterion("longitude is null");
			return (Criteria) this;
		}

		public Criteria andLongitudeIsNotNull() {
			addCriterion("longitude is not null");
			return (Criteria) this;
		}

		public Criteria andLongitudeEqualTo(Float value) {
			addCriterion("longitude =", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotEqualTo(Float value) {
			addCriterion("longitude <>", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThan(Float value) {
			addCriterion("longitude >", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeGreaterThanOrEqualTo(Float value) {
			addCriterion("longitude >=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThan(Float value) {
			addCriterion("longitude <", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeLessThanOrEqualTo(Float value) {
			addCriterion("longitude <=", value, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeIn(List<Float> values) {
			addCriterion("longitude in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotIn(List<Float> values) {
			addCriterion("longitude not in", values, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeBetween(Float value1, Float value2) {
			addCriterion("longitude between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andLongitudeNotBetween(Float value1, Float value2) {
			addCriterion("longitude not between", value1, value2, "longitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNull() {
			addCriterion("latitude is null");
			return (Criteria) this;
		}

		public Criteria andLatitudeIsNotNull() {
			addCriterion("latitude is not null");
			return (Criteria) this;
		}

		public Criteria andLatitudeEqualTo(Float value) {
			addCriterion("latitude =", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotEqualTo(Float value) {
			addCriterion("latitude <>", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThan(Float value) {
			addCriterion("latitude >", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeGreaterThanOrEqualTo(Float value) {
			addCriterion("latitude >=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThan(Float value) {
			addCriterion("latitude <", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeLessThanOrEqualTo(Float value) {
			addCriterion("latitude <=", value, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeIn(List<Float> values) {
			addCriterion("latitude in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotIn(List<Float> values) {
			addCriterion("latitude not in", values, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeBetween(Float value1, Float value2) {
			addCriterion("latitude between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andLatitudeNotBetween(Float value1, Float value2) {
			addCriterion("latitude not between", value1, value2, "latitude");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public static class Criterion {
		private String	condition;
		private Object	value;
		private Object	secondValue;
		private boolean	noValue;
		private boolean	singleValue;
		private boolean	betweenValue;
		private boolean	listValue;
		private String	typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

		/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deployments
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 03 15:25:33 CEST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}