package gov.polisen.orm.models;

public class CaseImage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caseimages.imageid
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	imageid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caseimages.caseid
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	caseid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column caseimages.deviceid
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	deviceid;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table caseimages
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public CaseImage(Integer imageid, Integer caseid, Integer deviceid) {
		this.imageid = imageid;
		this.caseid = caseid;
		this.deviceid = deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caseimages.imageid
	 * @return  the value of caseimages.imageid
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getImageid() {
		return imageid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caseimages.caseid
	 * @return  the value of caseimages.caseid
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getCaseid() {
		return caseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column caseimages.deviceid
	 * @return  the value of caseimages.deviceid
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getDeviceid() {
		return deviceid;
	}
}