package gov.polisen.orm.models;

import java.util.Date;

public class Case extends CaseKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.author
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.modificationtime
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Date	modificationtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.firstrevisioncaseid
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	firstrevisioncaseid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.firstrevisiondeviceid
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	firstrevisiondeviceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.deletiontime
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Date	deletiontime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.classification
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Short	classification;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.status
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Short	status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.priority
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Short	priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.longitude
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Float	longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.latitude
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Float	latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.timeofcrime
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Date	timeofcrime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cases.description
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private String	description;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cases
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Case(Integer deviceid, Integer caseid, Integer author,
			Date modificationtime, Integer firstrevisioncaseid,
			Integer firstrevisiondeviceid, Date deletiontime, Short classification,
			Short status, Short priority, Float longitude, Float latitude,
			Date timeofcrime, String description) {
		super(deviceid, caseid);
		this.author = author;
		this.modificationtime = modificationtime;
		this.firstrevisioncaseid = firstrevisioncaseid;
		this.firstrevisiondeviceid = firstrevisiondeviceid;
		this.deletiontime = deletiontime;
		this.classification = classification;
		this.status = status;
		this.priority = priority;
		this.longitude = longitude;
		this.latitude = latitude;
		this.timeofcrime = timeofcrime;
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.author
	 * @return  the value of cases.author
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.modificationtime
	 * @return  the value of cases.modificationtime
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Date getModificationtime() {
		return modificationtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.firstrevisioncaseid
	 * @return  the value of cases.firstrevisioncaseid
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getFirstrevisioncaseid() {
		return firstrevisioncaseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.firstrevisiondeviceid
	 * @return  the value of cases.firstrevisiondeviceid
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getFirstrevisiondeviceid() {
		return firstrevisiondeviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.deletiontime
	 * @return  the value of cases.deletiontime
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Date getDeletiontime() {
		return deletiontime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.classification
	 * @return  the value of cases.classification
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Short getClassification() {
		return classification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.status
	 * @return  the value of cases.status
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.priority
	 * @return  the value of cases.priority
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Short getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.longitude
	 * @return  the value of cases.longitude
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Float getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.latitude
	 * @return  the value of cases.latitude
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Float getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.timeofcrime
	 * @return  the value of cases.timeofcrime
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Date getTimeofcrime() {
		return timeofcrime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cases.description
	 * @return  the value of cases.description
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public String getDescription() {
		return description;
	}
}