package gov.polisen.orm.models;

import java.util.Date;

public class Deployment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deployments.id
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deployments.author
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deployments.modificationtime
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Date	modificationtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deployments.firstrevision
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	firstrevision;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deployments.deletiontime
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Date	deletiontime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deployments.status
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Short	status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deployments.priority
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Short	priority;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deployments.longitude
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Float	longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deployments.latitude
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Float	latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deployments.description
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private String	description;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deployments
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Deployment(Integer id, Integer author, Date modificationtime,
			Integer firstrevision, Date deletiontime, Short status, Short priority,
			Float longitude, Float latitude, String description) {
		this.id = id;
		this.author = author;
		this.modificationtime = modificationtime;
		this.firstrevision = firstrevision;
		this.deletiontime = deletiontime;
		this.status = status;
		this.priority = priority;
		this.longitude = longitude;
		this.latitude = latitude;
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deployments.id
	 * @return  the value of deployments.id
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deployments.author
	 * @return  the value of deployments.author
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deployments.modificationtime
	 * @return  the value of deployments.modificationtime
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Date getModificationtime() {
		return modificationtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deployments.firstrevision
	 * @return  the value of deployments.firstrevision
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getFirstrevision() {
		return firstrevision;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deployments.deletiontime
	 * @return  the value of deployments.deletiontime
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Date getDeletiontime() {
		return deletiontime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deployments.status
	 * @return  the value of deployments.status
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deployments.priority
	 * @return  the value of deployments.priority
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Short getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deployments.longitude
	 * @return  the value of deployments.longitude
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Float getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deployments.latitude
	 * @return  the value of deployments.latitude
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Float getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deployments.description
	 * @return  the value of deployments.description
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public String getDescription() {
		return description;
	}
}