package gov.polisen.orm.models;

public class Image {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images.id
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images.author
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column images.path
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private String	path;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table images
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Image(Integer id, Integer author, String path) {
		this.id = id;
		this.author = author;
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images.id
	 * @return  the value of images.id
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images.author
	 * @return  the value of images.author
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column images.path
	 * @return  the value of images.path
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public String getPath() {
		return path;
	}
}