package gov.polisen.orm.models;

public class Priority {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column priorities.id
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Short	id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column priorities.shorthand
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private String	shorthand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column priorities.description
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private String	description;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table priorities
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Priority(Short id, String shorthand, String description) {
		this.id = id;
		this.shorthand = shorthand;
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column priorities.id
	 * @return  the value of priorities.id
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Short getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column priorities.shorthand
	 * @return  the value of priorities.shorthand
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public String getShorthand() {
		return shorthand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column priorities.description
	 * @return  the value of priorities.description
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public String getDescription() {
		return description;
	}
}