package gov.polisen.orm.models;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private Integer	id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.username
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private String	username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.realname
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private String	realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.salt
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private String	salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.passwordhash
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	private String	passwordhash;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public User(Integer id, String username, String realname, String salt,
			String passwordhash) {
		this.id = id;
		this.username = username;
		this.realname = realname;
		this.salt = salt;
		this.passwordhash = passwordhash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.username
	 * @return  the value of users.username
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.realname
	 * @return  the value of users.realname
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.salt
	 * @return  the value of users.salt
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.passwordhash
	 * @return  the value of users.passwordhash
	 * @mbggenerated  Thu Apr 03 15:37:03 CEST 2014
	 */
	public String getPasswordhash() {
		return passwordhash;
	}
}